name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.2'
      
      - name: Cache Swift packages
        uses: actions/cache@v4.2.1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Verify SPM dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project PairPods.xcodeproj
          
      - name: Build
        run: |
          xcodebuild clean build -scheme PairPods -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: PairPods-Debug
          path: |
            build/Debug/PairPods.app
          retention-days: 7
