name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on macOS ${{ matrix.macos }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos: "13 (Ventura)"
            runner: macos-13
            xcode: "16.0"
          - macos: "14 (Sonoma)"
            runner: macos-14
            xcode: "16.0"
          - macos: "15 (Sequoia)"
            runner: macos-15
            xcode: "16.2" 
          - macos: "Latest"
            runner: macos-latest
            xcode: "latest-stable"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ matrix.xcode }}
      
      - name: Cache Swift packages
        uses: actions/cache@v4.2.1
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.runner }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.runner }}-spm-
      
      - name: Verify SPM dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project PairPods.xcodeproj
          
      - name: Build
        run: |
          xcodebuild clean build -scheme PairPods -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: PairPods-${{ matrix.macos }}-Debug
          path: |
            build/Debug/PairPods.app
          retention-days: 7