name: CI
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build on macOS ${{ matrix.macos }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos: "15 (Sequoia)"
            runner: macos-15
            xcode: "16.0"
            arch: "Universal"
          - macos: "Latest"
            runner: macos-latest
            xcode: "latest-stable"
            arch: "Universal"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ matrix.xcode }}
      
      - name: Cache Swift packages
        uses: actions/cache@v4.2.1
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.runner }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.runner }}-spm-
      
      - name: Verify SPM dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project PairPods.xcodeproj
          
      - name: Build
        run: |
          xcodebuild clean build -scheme PairPods -configuration Debug -derivedDataPath ./DerivedData CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ARCHS="x86_64 arm64" ONLY_ACTIVE_ARCH=NO
      
      - name: Verify app architectures
        run: |
          lipo -info ./DerivedData/Build/Products/Debug/PairPods.app/Contents/MacOS/PairPods
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: PairPods-${{ matrix.macos }}-${{ matrix.arch }}-Debug
          path: |
            ./DerivedData/Build/Products/Debug/PairPods.app
          retention-days: 7